#! /usr/bin/env bash
export LIRE_LIBPATH="$HOME"/lib/lire
export LIRE_BINPATH="$HOME"/bin
export NOWEB_LIBPATH=/usr/lib/noweb

echo "*** Making lire..."
make
echo "--> Done"
exit
echo "*** Installing lire..."
make install
echo "--> Done"
echo "*** Using lire to tangle and weave lire..."
lire lire.lir --bibliography=lire.bib
echo "--> Done"
echo "*** Weaved document is in lire.html ***"
