#! /usr/bin/env bash
export LIR_LIBPATH="$HOME"/lib/lir
export LIR_BINPATH="$HOME"/bin
export NOWEB_LIBPATH=/usr/lib/noweb

mkdir --parents "$LIR_LIBPATH"
mkdir --parents "$LIR_BINPATH"

echo "*** Making lir..."
make
echo "--> Done"
echo "*** Installing lir..."
make install
echo "--> Done"
rm -r .lir
echo "*** Using lir to tangle and weave lir..."
lir lir.lir --bibliography=lir.bib
echo "--> Done"
echo "*** Weaved document is in lir.html ***"
